# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soldier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsoldier.proto\"U\n\x14SoldierMatrixRequest\x12\x12\n\nfield_size\x18\x01 \x01(\x05\x12\x13\n\x0bNum_soldier\x18\x02 \x01(\x05\x12\t\n\x01t\x18\x03 \x01(\x05\x12\t\n\x01T\x18\x04 \x01(\x05\"G\n\x15SoldierMatrixResponse\x12\x12\n\nmatrix_row\x18\x01 \x03(\t\x12\x1a\n\x08soldiers\x18\x02 \x03(\x0b\x32\x08.Soldier\"_\n\x07Soldier\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05speed\x18\x04 \x01(\x05\x12\x14\n\x0cis_commander\x18\x05 \x01(\x08\x12\r\n\x05\x61live\x18\x06 \x01(\x08\"E\n\x0bMoveRequest\x12\x12\n\nsoldier_id\x18\x01 \x01(\x05\x12\x10\n\x08target_x\x18\x02 \x01(\x05\x12\x10\n\x08target_y\x18\x03 \x01(\x05\"\x0e\n\x0cMoveResponse2|\n\x14SoldierMatrixService\x12?\n\x0eGenerateMatrix\x12\x15.SoldierMatrixRequest\x1a\x16.SoldierMatrixResponse\x12#\n\x04Move\x12\x0c.MoveRequest\x1a\r.MoveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'soldier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SOLDIERMATRIXREQUEST']._serialized_start=17
  _globals['_SOLDIERMATRIXREQUEST']._serialized_end=102
  _globals['_SOLDIERMATRIXRESPONSE']._serialized_start=104
  _globals['_SOLDIERMATRIXRESPONSE']._serialized_end=175
  _globals['_SOLDIER']._serialized_start=177
  _globals['_SOLDIER']._serialized_end=272
  _globals['_MOVEREQUEST']._serialized_start=274
  _globals['_MOVEREQUEST']._serialized_end=343
  _globals['_MOVERESPONSE']._serialized_start=345
  _globals['_MOVERESPONSE']._serialized_end=359
  _globals['_SOLDIERMATRIXSERVICE']._serialized_start=361
  _globals['_SOLDIERMATRIXSERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
